<?php

namespace ContainerZuXZ5EU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaviconControllerService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'MonterHealth\ApiFilterBundle\Tests\Application\Controller\FaviconController' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\Tests\Application\Controller\FaviconController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/tests/Application/Controller/FaviconController.php';

        return $container->services['MonterHealth\\ApiFilterBundle\\Tests\\Application\\Controller\\FaviconController'] = new \MonterHealth\ApiFilterBundle\Tests\Application\Controller\FaviconController();
    }
}
