<?php

namespace ContainerZuXZ5EU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonterHealthApiFilter_ApiFilterFactoryService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'monter_health_api_filter.api_filter_factory' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\Attribute\ApiFilterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Attribute/ApiFilterFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Attribute/Reader.php';

        return $container->services['monter_health_api_filter.api_filter_factory'] = new \MonterHealth\ApiFilterBundle\Attribute\ApiFilterFactory(($container->services['monter_health_api_filter.attribute_reader'] ??= new \MonterHealth\ApiFilterBundle\Attribute\Reader()));
    }
}
