<?php

namespace ContainerZuXZ5EU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderFilterService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'MonterHealth\ApiFilterBundle\Filter\OrderFilter' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\Filter\OrderFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Filter/Filter.php';
        include_once \dirname(__DIR__, 4).'/src/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/src/Filter/Order.php';
        include_once \dirname(__DIR__, 4).'/src/Filter/OrderFilter.php';

        return $container->privates['MonterHealth\\ApiFilterBundle\\Filter\\OrderFilter'] = new \MonterHealth\ApiFilterBundle\Filter\OrderFilter();
    }
}
