<?php

namespace ContainerDXSpbME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'MonterHealth\ApiFilterBundle\Tests\Application\Controller\BookController' shared autowired service.
     *
     * @return \MonterHealth\ApiFilterBundle\Tests\Application\Controller\BookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/tests/Application/Controller/BookController.php';

        return $container->services['MonterHealth\\ApiFilterBundle\\Tests\\Application\\Controller\\BookController'] = new \MonterHealth\ApiFilterBundle\Tests\Application\Controller\BookController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['monter_health_api_filter.monter_health_api_filter'] ?? $container->load('getMonterHealthApiFilter_MonterHealthApiFilterService')));
    }
}
