<?php

namespace ContainerDXSpbME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonterHealthApiFilter_MonterHealthApiFilterService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'monter_health_api_filter.monter_health_api_filter' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\MonterHealthApiFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/MonterHealthApiFilter.php';
        include_once \dirname(__DIR__, 4).'/src/Parameter/Factory/ParameterCollectionFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Parameter/Factory/DefaultParameterCollectionFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Util/QueryNameGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Util/QueryNameGenerator.php';

        $container->services['monter_health_api_filter.monter_health_api_filter'] = $instance = new \MonterHealth\ApiFilterBundle\MonterHealthApiFilter(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\BooleanFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\BooleanFilter());
            yield 1 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\SearchFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\SearchFilter());
            yield 2 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\OrderFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\OrderFilter());
            yield 3 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\NumericFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\NumericFilter());
            yield 4 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\RangeFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\RangeFilter());
            yield 5 => ($container->privates['MonterHealth\\ApiFilterBundle\\Filter\\DateFilter'] ??= new \MonterHealth\ApiFilterBundle\Filter\DateFilter());
        }, 6), ($container->services['monter_health_api_filter.api_filter_factory'] ?? $container->load('getMonterHealthApiFilter_ApiFilterFactoryService')), ($container->services['monter_health_api_filter.parameter_collection_factory'] ??= new \MonterHealth\ApiFilterBundle\Parameter\Factory\DefaultParameterCollectionFactory()), ($container->privates['monter_health_api_filter.query_name_generator'] ??= new \MonterHealth\ApiFilterBundle\Util\QueryNameGenerator()));

        $instance->setConfigs(['order_parameter_name' => 'order', 'default_order_strategy' => 'ascending', 'parameter_collection_factory' => NULL, 'attribute_reader' => NULL, 'api_filter_factory' => NULL]);

        return $instance;
    }
}
