<?php

namespace ContainerDXSpbME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonterHealthApiFilter_QueryNameGeneratorService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'monter_health_api_filter.query_name_generator' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\Util\QueryNameGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Util/QueryNameGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Util/QueryNameGenerator.php';

        return $container->privates['monter_health_api_filter.query_name_generator'] = new \MonterHealth\ApiFilterBundle\Util\QueryNameGenerator();
    }
}
