<?php

namespace ContainerDXSpbME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonterHealthApiFilter_ParameterCollectionFactoryService extends MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'monter_health_api_filter.parameter_collection_factory' shared service.
     *
     * @return \MonterHealth\ApiFilterBundle\Parameter\Factory\DefaultParameterCollectionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Parameter/Factory/ParameterCollectionFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Parameter/Factory/DefaultParameterCollectionFactory.php';

        return $container->services['monter_health_api_filter.parameter_collection_factory'] = new \MonterHealth\ApiFilterBundle\Parameter\Factory\DefaultParameterCollectionFactory();
    }
}
