<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuXZ5EU\MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuXZ5EU/MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZuXZ5EU.legacy');

    return;
}

if (!\class_exists(MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZuXZ5EU\MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer::class, MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer::class, false);
}

return new \ContainerZuXZ5EU\MonterHealth_ApiFilterBundle_Tests_Application_KernelDevDebugContainer([
    'container.build_hash' => 'ZuXZ5EU',
    'container.build_id' => '4e121ca3',
    'container.build_time' => 1774473766,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuXZ5EU');
